server:
  port: 9090

spring:
  application:
    name: core-service
    version: 1.0.0
  jackson:
    time-zone: America/Sao_Paulo
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:postgresql://localhost:5432/connectfood
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: core
        format_sql: true
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    default-schema: core
    schemas: core
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    web: error
